### ISSUE TITLE
This module is not loading under Windows (any more)

### ISSUE THREAD

**Issue by plasticut** [gruntjs/grunt-contrib-watch#102]
GruntJs writes message:

Loading "watch.js" tasks...ERROR
Error: No such module

I think the problem is in the file watch.js `process.on('SIGINT', function() {`

**Comment by dbilovd** [comment]
@shama what's the fix?

**Comment by shama** [comment]
@dbilovd Ha no idea, that was over 3 years ago :)

**Comment by dbilovd** [comment]
@shama okay. Experiencing this. On OSX too :-(

**Comment by dbilovd** [comment]
Reinstalling watch fixed it for me.
1.  npm uninstall grunt-contrib-watch
2. npm cache clean
3. npm install --save-dev grunt-contrib-watch
