### ISSUE TITLE
Cannot get watch working. - Exits without message.

### ISSUE THREAD

**Issue by William-Owen** [gruntjs/grunt-contrib-watch#110]
I am attempting to use the watch (with livereload). When running the 'grunt watch' command from the terminal however the process exists immediately with no message. I expected there process to remain open with a server started to support the watch and livereload. (https://github.com/gruntjs/grunt-contrib-watch)

I am using Mac OSX Mountain Lion, grunt-cli v0.1.8, grunt v0.4.1

My Gruntfile can be seen here: https://gist.github.com/William-Owen/5626741

Any and all help appreciated.

**Comment by lrabuffetti** [comment]
I've got the next gruntfile

module.exports = function(grunt) {
    
    'use strict';

    // Load Grunt tasks declared in the package.json file
    require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks);

    // Configure Grunt
    grunt.initConfig({

        // Grunt express - our webserver
        // https://github.com/blai/grunt-express
        express: {
            all: {
                options: {
                    bases: 'xxxxxxxxxxxx',
                    port: 9000,
                    hostname: '0.0.0.0',
                    livereload: true
                }
            }
        },

        // grunt-watch will monitor the projects files
        // https://github.com/gruntjs/grunt-contrib-watch
        watch: {
            all: {
                    files: [
                        '**/*.html', 
                        '**/*.css', 
                        '!**/node_modules/**', 
                        '!/sdk', 
                        '!**/sdk/**'
                    ],
                    options: {
                        livereload: true
                }
            }
        },

        // grunt-open will open your browser at the project's URL
        // https://www.npmjs.org/package/grunt-open
        open: {
            all: {
                path: 'http://localhost:9000/index.html'
            }
        },

        // grunt-open will install the bower components defined on the bower.json file
        // https://www.npmjs.com/package/grunt-bower-install-simple
        'bower-install-simple': {
            options: {
                color: true,
                directory: 'assets/bower_components'
            },
            'prod': {
                options: {
                    production: true
                }
            },
            'dev': {
                options: {
                    production: false
                }
            }
        }
    });

    // Creates the `server` task
    grunt.registerTask('server', [
        'express',
        'open',
        'watch'
        ]);
};

I modify to not watch what's inside the sdk (if I remove the node_modules from it, it works) , but I have the error , Running "watch" task Waiting... Warning: Maximum call stack size exceeded, I follow the next explanation/solution, but I can not get it work, http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

any suggestion?
