### ISSUE TITLE
Running Watch and Connect example

### ISSUE THREAD

**Issue by William-Owen** [gruntjs/grunt-contrib-watch#111]
I am trying to run both watch with livereload and a basic web server. I found the connect server module but it seems as though both the watch task and the connect task block further tasks from running resulting in only one of them starting. 

I have tired

```
 grunt.registerTask('dev', ['connect', 'watch']);
```

and

```
    grunt.registerTask('dev', ['watch', 'connect']);
```

Is there an example of how to do this somewhere. I feel it must but be a common requirement.

**Comment by dajbd** [comment]
这个帖子早就解决了我的问题，我却始终傻傻地没看懂。
我心情沉重的接受了一个事实：我是傻逼。
一次次为自己的智商担忧……

**Comment by dajbd** [comment]
Watch and Connect同时运行，
把Connect的配置：   keepalive属性值改为false即可。
keepalive为true，watch任务是不会运行的。
这样就解决了Watch 失败的问题。

**Comment by dajbd** [comment]
thank you so much
