### ISSUE TITLE
Warning: Task "compass" not found. Use --force to continue.

### ISSUE THREAD

**Issue by ldexterldesign** [gruntjs/grunt-contrib-watch#294]
Hey,

Is anyone able to help me fix this error? It's quite annoying as my terminal pops everytime I save out my code?

![screen shot 2014-02-24 at 18 43 09](https://f.cloud.github.com/assets/1715809/2249328/b92b356c-9d83-11e3-8d7a-7f465c17f8df.png)

![screen shot 2014-02-24 at 18 43 18](https://f.cloud.github.com/assets/1715809/2249333/bcc28838-9d83-11e3-88c6-479ad33b0843.png)

Yours hopefully,

**Comment by thowar2** [comment]
I had the same error, which I solved by installing the compass ruby gem: `sudo gem install compass`

**Comment by rogerywoo** [comment]
I also had the same problem on Windows.  After installing compass, make sure your path includes the path to ruby.

**Comment by baranirajarathinam** [comment]
I am also getting the same Warning: not found: compass Use --force to continue.
![image](https://cloud.githubusercontent.com/assets/13750636/23011725/9162ad84-f448-11e6-85eb-757d7bf6b43d.png)
i tried installing the compass seperately as well, no luck.  Also, what do you mean by "make sure your path includes the path to ruby."?

**Comment by rogerywoo** [comment]
Your PATH environment variable needs to include the directory where Ruby was installed.

**Comment by jeremylv1992** [comment]
I install yo and yo angular. Here is a angular project, I run "grunt server" > get the same error.

![image](https://user-images.githubusercontent.com/7057383/27853753-990c2f68-6196-11e7-90d7-55dfce423200.png)

**Comment by arsenk01** [comment]
I had the sam problem on Windows and running `gem install compass` fixed the problem.

**Comment by lili0allen** [comment]
try the solution https://github.com/Compass/compass/issues/2129#issuecomment-334047499
