### ISSUE TITLE
changed event fired twice when file saved

### ISSUE THREAD

**Issue by jeffschwartz** [gruntjs/grunt-contrib-watch#324]
When I save a file, watch runs my task twice. My environment is:
node v0.10.26
grunt v0.4.4
watch v0.6.1
less v0.11.0

My package.json file:
{
  "name": "preamble",
  "version": "2.0.0",
  "devDependencies": {
    "grunt": "~0.4.4",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-contrib-less": "^0.11.0"
  }
}

My Gruntfile.js:
module.exports = function ( grunt ) {

```
// Project configuration.
grunt.initConfig({
    pkg    : grunt.file.readJSON( 'package.json' ),
    less   : {
        production  : {
            files : {
                "stylesheets/preamble.css" : "stylesheets/preamble.less"
            }
        }
    },
    watch  : {
        scripts : {
            files   : ['stylesheets/preamble.less'],
            tasks   : ['less:production'],
            options : {
                interrupt : true
            }
        }
    }
});

// Load the plugins
grunt.loadNpmTasks( 'grunt-contrib-less' );
grunt.loadNpmTasks( 'grunt-contrib-watch' );

// Default task(s).
grunt.registerTask( 'default', ['watch'] );

// Alias Tasks
//grunt.registerTask( 'dev', 'Running Grunt dev', ['less:production', 'concat:dist', 'imagemin'] );
//grunt.registerTask( 'prod', 'Running Grunt prod', ['less:production', 'concat:dist', 'uglify:prod', 'imagemin'] );
```

};

Console Output:
Jeffrey’s iMac:preamble jeffrey$ grunt
Running "watch" task
Waiting...

> > File "stylesheets/preamble.less" changed.
> > Running "less:production" (less) task
> > File stylesheets/preamble.css created: 0 B → 1.71 kB

Done, without errors.
Completed in 0.480s at Fri Apr 18 2014 00:30:06 GMT-0400 (EDT) - Waiting...

> > File "stylesheets/preamble.less" changed.
> > Running "less:production" (less) task
> > File stylesheets/preamble.css created: 0 B → 1.71 kB

Done, without errors.
Completed in 0.477s at Fri Apr 18 2014 00:30:07 GMT-0400 (EDT) - Waiting...

As per the above console output, saving the file in my editor (in my case, Vim) causes the less task to be run twice.

**Comment by ekkis** [comment]
this doesn't work for me on OSX 10.11.2 (El Capitan).  I'm running vim 7.3, node 5.0.0, grunt 0.4.5 and grunt-contrib-watch 0.6.1
