### ISSUE TITLE
More watched than expected

### ISSUE THREAD

**Issue by BBosman** [gruntjs/grunt-contrib-watch#328]
I'm new to using grunt-contrib-watch and wanted to start of by having it watch my Gruntfile, but I'm seeing some strange behaviour.

I have this configuration in my Gruntfile:

``` js
watch: {
  build: {
    files: ['Gruntfile.js'],
    tasks: ['jshint:build', 'jscs:build']
  }
}
```

If I run this with --verbose I get:

```
Running "watch" task
Waiting...
Verifying property watch exists in config...OK
Verifying property watch.build.files exists in config...OK
Watching Gruntfile.js for changes.
Watching .git for changes.
Watching .nuget for changes.
Watching Azure for changes.
Watching Cordova for changes.
Watching node_modules for changes.
Watching packages for changes.
Watching WebApp for changes.
```

Next to the Gruntfile.js it's also watching all directories in that directory. Is this intended behaviour? 
As those .git and node_modules directories are quite large I think this could have an impact on performance.

My setup is:
OS: Windows 8.1
Node: 0.10.26
Grunt: 0.4.4
Grunt-contrib-watch: 0.6.1

**Comment by andyexeter** [comment]
Just out of curiosity, why does it need to "watch certain folders in case a file is added to them" if you've specified you only want to watch one file in a particular location? 

I mean, if I've specified in my config that I only want to watch the top level `Gruntfile.js` file then aren't other files that might be added in different directories irrelevant to the task?

**Comment by shama** [comment]
@andyexeter It doesn't know that the string `Gruntfile.js` means only that single file and it already exists. For example if you were watching the file `app/index.js` and it didn't exist, we wouldn't know to trigger a `added` event when you added that file to the `app/` folder if it wasn't watched behind the scenes.

There are definitely further optimizations we could make to this all but that is the reason as it stands.

**Comment by andyexeter** [comment]
@shama Thanks for clarifying. For the record, I also tried specifying the file in the task config like 
`files: [ './Gruntfile.js' ]` so it'd know I'm only interested in the one top level file but it didn't make a difference.

**Comment by shama** [comment]
@andyexeter Correct and keep in mind, the array of strings being passed to `files` are *file patterns* and not *file paths.* Also it is only watching those folders (and not the files within those folders), so unless you have 1000s of folders in the same folder as your `Gruntfile.js`, it should be ok.
