### ISSUE TITLE
grunt watch blocks the compilation of Visual Studio project

### ISSUE THREAD

**Issue by etylsarin** [gruntjs/grunt-contrib-watch#341]
It would be great to have Visual Studio automatically run grunt watch for a specific solution or project once it's opened. Now, when fired from MSBuild BeforeCompile target, it simply blocks the compilation and prevent VS from responding.

**Comment by crperez5** [comment]
@etylsarin you should attach to the open project event. This way your build isn't blocked and you can watch for file changes at the same time. Cheers

**Comment by etylsarin** [comment]
thanks @crperez5.
I would say this issue can be closed now.
