### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by flynfish** [gruntjs/grunt-contrib-watch#35]
When running grunt watch, the process sits around 70% cpu usage on my mac (10.8.2). Is this a known issue?

**Comment by timomayer** [comment]
i have the same issue!

**Comment by pwdonald** [comment]
I am also experiencing this issue. It starts out running at around 10-20%, then after about five minutes it shoots up to 99% CPU and stays there until I stop the watch task. I was unaware this was happening on my desktop but when I run it on my laptop it gets very warm and the fan spins constantly, which is what alerted me to the issue.

**Comment by timomayer** [comment]
@pwdonald exactly same for me. but i have node_modules excluded already...

**Comment by jifeon** [comment]
Have the same problem on Yosemite on mac mini, 50% CPU for couple hundreds of scripts. I use the same configuration on fedora and grunt uses less than 1%

**Comment by jifeon** [comment]
I've found out that updating gaze to 0.6.4 solves my issue. PR about it: #412

**Comment by jmorvan** [comment]
@tikosar spot on! I was watching node_modules! tku

**Comment by DominikDitoIvosevic** [comment]
I've had the issue of watching node_modules/ as well. I've added 

       '!node_modules/**/*.*'

like:

        watch: {
            options: {
                livereload: true
            },
            express: {
                files: ['**/*.js', '!node_modules/**/*.*'],

Should you maybe disable watching node_modules/ by default since I don't see why anyone would do that anyways and they could always enable it manually

**Comment by yang** [comment]
I'm seeing the same disparity in CPU usage between Linux and Mac.  I'm using 0.6.1.

**Comment by WayneKeenan** [comment]
obviously, ymmv, but just thought I mention another potential biggie that caused slowdown on my Mac which was solved by ignoring the bower_components folder, e.g.  '!app/bower_components/**/*.*'

before :  ~3100 files using ~%60 CPU usage
after:   ~10 files using ~5% CPU usage

versions:
  
grunt-contrib-watch v0.6.1
grunt-cli v0.1.13
grunt v0.4.5
node v5.5.0

I would have thought watching 3100 files would not be such a problem giving the Mac's FSEvent API is supposed to be fast and light weight. 

But, I've just noticed that the grunt-contrib-watch package.json doesn't explicitly mention the node module https://www.npmjs.com/package/fsevents as a dependancy and uses gaze.

I guess a potential fix (for very large projects) is to use fsevent on Mac (either directly in grunt-watch or by patching node's gaze)

**Comment by rbosneag** [comment]
My special dumb case:

Took me 3h (of looking in `watch` source and `gaze` and resetting `Gruntfile.js` to a minimum and update packages one by one and changing versions, etc) to realize that my task was configured as follows:

    grunt.registerTask('watch', ['watch']);

Guess what? Recursion! CPU went in 100% instantly, no info in terminal, verbose mode showed watch task running continuously. 

That was stupid but made me laugh in the end. 

I don't think my solution will help someone but I posted it just to cover all scenarios...

**Comment by saltcod** [comment]
Someone had composer'd a /vendor/ dir in my theme.  Ignoring that with '!**/vendor/**' did the trick for me.  Thanks!
