### ISSUE TITLE
live reload not working

### ISSUE THREAD

**Issue by nil4you** [gruntjs/grunt-contrib-watch#362]
Hi,

I have tried as your documentation. It can watch the changes but browser do not auto reload on change.

Can you fix this issue. And also can it be issue of admin rights ?

**Comment by icese7en** [comment]
@nil4you and I have same problem, the network shows the files have updated but the browser not refresh. Just in case when css changes but the js works fine.

**Comment by nil4you** [comment]
For me both are not working in my home pc . I have to do manual refresh.
While in office PC it works as great as hell.

**Comment by emailwizardry** [comment]
I was having this exact same problem. I only just fixed it and I'm not 100% sure how!

I ended up typing `lsof -iTCP:35729` into Terminal (as per the instructions on [this page](http://feedback.livereload.com/knowledgebase/articles/86181-failed-to-start-port-occupied) so that I could see if anything else was running on the port (since I have the actual LiveReload app installed as well as the browser extension and I've used it in the past). That showed me that Chrome was using the port and also had the line `localhost:61715->localhost:35729` and I put `localhost:61715` into my browser thinking that it might show me my files, but nothing loaded.

So I quit Chrome and typed `lsof -iTCP:35729` into Terminal again to verify that, once Chrome was closed, nothing was trying to use that port. It output nothing, as expected.

Then I fired Chrome back up again, opened my HTML file (just at its file:///Users/.. address, not even at localhost) and typed `grunt watch -v` into terminal again, changed my file, and it was working!

I have no idea why. But I thought I would share anyway.. just in case.

Maybe I had already fixed it before and Chrome just needed a restart.. in any case it was good to learn how to check whether the LiveReload port is occupied.

**Comment by ambodi** [comment]
@nil4you Guys, you're not gonna believe this but I ran into the same issue and my fix was crazy: Chrome Cache! By chance, I tested the code in my other Chrome Person profile and I saw it works, I emptied the cache and it came back live! :scream: :scream: :scream:

**Comment by victorxw** [comment]
I was having the similar problem until I went over the `connect-livereload` documentation closely. It says
<blockquote>
In your connect or express application add this after the static and before the dynamic routes. If you need liveReload on static html files, then place it before the static routes.
</blockquote>
Previously, I was putting the line `app.use(require('connect-livereload')());` in the end of my `app.js` file where dynamic routes have been configured and loaded. Moving this line after `app.use(express.static(config.root + '/public'));` works!!

Hope it helps.

**Comment by pfernandez** [comment]
>liver reload not working

Try *live* reload instead. Liver reload can be have undesirable long-term side effects.

**Comment by shama** [comment]
![badumtss](https://cloud.githubusercontent.com/assets/99604/8842725/a02390fa-30b2-11e5-8c16-d98634cdf079.png)

**Comment by nil4you** [comment]
:)

**Comment by nil4you** [comment]
whatever you say, it's damn working on office pc not on home PC. Which has very high config. :(

**Comment by pritic** [comment]
Any luck?

**Comment by nil4you** [comment]
Haven't any. I think mine one is rare case. it's almost working for other
ones.

On Wed, Aug 19, 2015 at 4:03 PM, Priti Changlani <notifications@github.com>
wrote:

> Any luck?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gruntjs/grunt-contrib-watch/issues/362#issuecomment-132820028>
> .
>



-- 
With Regards,
Nirmal Bhagwani.

**Comment by m00s** [comment]
Empty the chrome cache solved for me. Thanks @ambodi you saved my day, even 6 months later :+1:

**Comment by nil4you** [comment]
it never solved for me, but it's not a definitely developing code issue. so closing it.

**Comment by Shobhit-Agrawal** [comment]
I added the scrip tag 
<script src="http://localhost:35729/livereload.js"></script>
and it started working.

**Comment by karan1276** [comment]
@nil4you i am having the same issue, i'll let you guys know if i find a solution.

**Comment by Shobhit-Agrawal** [comment]
for me I added this line and started working
<script src="http://localhost:35729/livereload.js"></script>

**Comment by Shobhit-Agrawal** [comment]
This line `<script src="http://localhost:35729/livereload.js"></script>`

**Comment by chandradeochakravarti** [comment]
File path -> task/config/watch.js

module.exports = function(grunt) {

	grunt.config.set('watch', {
		api: {

			// API files to watch:
			files: ['api/**/*']
		},
		assets: {

			// Assets to watch:
			files: ['assets/**/*', 'tasks/pipeline.js'],
			files: ['assets/**/**/*', 'tasks/pipeline.js'],

			// When assets are changed:
			tasks: ['syncAssets' , 'linkAssets']
		}
		livereload: {
		  	options: {
		    	livereload: true
		  	},
		  	files: [
		    	'assets/**/*',
		    	'assets/**/**/*'
		  	]
		},
		options: {
	    	interrupt: true,
	    	debounceDelay: 250,
	    	reload: true,
	    	livereload: true
	    }
	});

	grunt.loadNpmTasks('grunt-contrib-watch');
};

File path -> view/layout.ejs
<head>
       <script src="http://localhost:35729/livereload.js"></script>
</head>

Start watcher
    $ grunt watch -v

try once.

:)

**Comment by cbillowes** [comment]
I don't know if this will help anyone but if you have livereload set to a port, make sure the same port is set in the watch config. 

Just having it as true didn't seem to work for me. When I updated it to the port it started working again.

**Comment by DarynHolmes** [comment]
I was missing the script ```<head> <script src="http://localhost:35729/livereload.js"></script> </head>```. Adding that fixed it for me...

**Comment by ArminSheng** [comment]
@DarynHolmes  Me too...but actually don't have to add that, maybe sth wrong.

**Comment by RajniShriramoji** [comment]
hi for me also same problem. In console (command prompt) its showing the all changes so it means watch is working. But the browser page is not reloading. Any suggestion will help me.

**Comment by BeekeeperHub** [comment]
**// WITHOUT LOCAL SERVER**
1. Use browser extension http://livereload.com/extensions/. 
2. Install the extension. 
3. After you installed, for Chrome users: settings > extensions > LiveReload > Allow access to file URLs (check)
4. In your browser you should see the icon top right. Click to activate. It is hard to notice, but if you look at the small circle in the center of the icon is the on/off switch.
5. Make changes to your file and you should see the page reloads.
6. I have livereload set to true, `options: {livereload: true}` and i have not added the script tag in the .html file.
Note: Watch this video where Dave McFarland explains that you need to have a extension to make the reload work. [https://www.youtube.com/watch?v=JMkMTt2-pm0](url)

**// WITH LOCAL SERVER** 
1. follow the same steps from below, and you do not have to check the 'Allow access to file URLs '. Whether it is checked or not, your page automatically works.
2. MAKE SURE YOU REFRESH THE PAGE, and turn on the extension.

**Comment by ynr1** [comment]
Same issue I too faced and i have solved by following script.
Try this in you index.html or your main page. 

<script> document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>') </script>
