### ISSUE TITLE
ie9 not supported

### ISSUE THREAD

**Issue by climboid** [gruntjs/grunt-contrib-watch#379]
when running this task as part of a yeoman generator I get the following error in IE9

```
LiveReload disabled because the browser does not seem to support web sockets 
SCRIPT5007: Unable to get value of the property 'addPlugin': object is null or undefined 
livereload.js?snipver=1, line 961 character 5
```
Any help on how to fix this is much appreciated.
Thank you

**Comment by adyz** [comment]
Same here

**Comment by arthurvr** [comment]
The error message nails it, isn't it?

> LiveReload disabled because the browser does not seem to support web sockets 

[IE9 just is one of the browsers not supporting web sockets,](http://caniuse.com/#search=web%20sockets) and thus, livereload does not support IE9.

**Comment by rvanbaalen** [comment]
Well thats pretty clear indeed @arthurvr :wink: I think this issue can be closed.

**Comment by arthurvr** [comment]
@shama @sindresorhus @mrjoelkemp Can somebody close this? :smiling_imp:
