### ISSUE TITLE
Running "watch" task Waiting... Fatal error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by RDash20** [gruntjs/grunt-contrib-watch#382]
During the watch task I keep running into this error:

Running "watch" task
Waiting...
Fatal error: connect ECONNREFUSED
Fatal error: socket hang up

I have no idea what is causing this.

**Comment by Techture** [comment]
Hi @shama, I'm having an issue with grunt serve hanging up and I've never had this issue before. Can you please help. 

I also have this error when running grunt serve:
Warning: Unable to create directory "C:\Users\Techture\Documents\_JWT\Zyrtec\html_banners\Zyrtec_Addressables_0116\Childrens\300x250\Zyrtec_Kids_300x250\.tmp" (Error code: EPERM).

Any help is greatly appreciated :)

Thanks!

Here's my grunt file code:

`'use strict';
var LIVERELOAD_PORT = 35729;
var SERVER_PORT = 9000;
var lrSnippet = require('connect-livereload')({
    port: LIVERELOAD_PORT
});
var mountFolder = function(connect, dir) {
    return connect.static(require('path').resolve(dir));
};

module.exports = function(grunt) {

    // show elapsed time at the end
    require('time-grunt')(grunt);
    // load all grunt tasks
    require('load-grunt-tasks')(grunt);

    // configurable paths
    var pathConfig = {
        dev: 'dev',
        dist: 'dist',
        tmp: '.tmp'
    };

    var pkgVars = require('./package.json');

    // Project configuration.
    grunt.initConfig({
        // Server and compass
        pkg: pkgVars,
        path: pathConfig,
        watch: {
            options: {
                nospawn: true,
                livereload: true
            },
            compass: {
                files: ['<%= path.dev %>/styles/{,*/}*.{scss,sass}'],
                tasks: ['compass']
            },
            livereload: {
                options: {
                    livereload: grunt.option('livereloadport') || LIVERELOAD_PORT
                },
                files: [
                    '{<%= path.tmp %>}/*.html',
                    '{<%= path.tmp %>}{,*/}*.css',
                    '{<%= path.tmp %>}{,*/}*.js',
                    '{<%= path.tmp %>/data/{,*/}*.json',
                    '<%= path.tmp %>{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
                ]
            },
            src: {
                files: [
                    '{<%= path.tmp %>,<%= path.dev %>}/*.html',
                    '{<%= path.tmp %>}/styles/{,*/}*.css',
                    '{<%= path.tmp %>,<%= path.dev %>}/js/{,*/}*.js',
                    '{<%= path.tmp %>,<%= path.dev %>}/data/{,*/}*.json',
                    '<%= path.dev %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
                ],
                tasks: ['serve:dist'],
            }
        },
        config: {
            dev: {
                options: {
                    variables: {
                        'environment': 'development'
                    }
                }
            },
            prod: {
                options: {
                    variables: {
                        'environment': 'production'
                    }
                }
            }

        },
        connect: {
            options: {
                port: grunt.option('port') || SERVER_PORT,
                // change this to '0.0.0.0' to access the server from outside
                hostname: '0.0.0.0'
            },
            livereload: {
                options: {
                    middleware: function(connect) {
                        return [
                            lrSnippet,
                            mountFolder(connect, pathConfig.tmp),
                            mountFolder(connect, pathConfig.dev)
                        ];
                    }
                }
            },
            dist: {
                options: {
                    middleware: function(connect) {
                        return [
                            mountFolder(connect, pathConfig.dist)
                        ];
                    }
                }
            }
        },
        cachebreaker: {
            dist: {
                options: {
                    match: ['app.js', 's.css']
                },
                files: {
                    src: ['<%= path.dist %>/index.html']
                }
            }
        },
        open: {
            server: {
                path: 'http://localhost:<%= connect.options.port %>'
            }
        },
        compass: {
            options: {
                sassDir: '<%= path.dev %>/styles',
                cssDir: '<%= path.tmp %>/styles',
                imagesDir: '<%= path.dev %>/images',
                javascriptsDir: '<%= path.dev %>/js',
                fontsDir: '<%= path.dev %>/styles/fonts',
                relativeAssets: true
            },
            dist: {},
            server: {
                options: {
                    debugInfo: true
                }
            }
        },

        // Metadata.
        clean: {
            dist: ['<%= path.tmp %>', '<%= path.dist %>/*'],
            server: '<%= path.tmp %>'
        },
        replace: {
            env: {
                options: {
                    variables: {
                        'environment': '<%= grunt.config.get("environment") %>'
                    },
                    force: true
                },
                files: [{
                    expand: true,
                    flatten: true,
                    src: ['<%= path.dev %>/js/app.js', '<%= path.dev %>/index.html'],
                    dest: '<%= path.tmp %>'
                }]
            },
            post: {
                options: {
                    patterns: [{
                        match: /(([\./]*)?(images)\/)/g,
                        replacement: ''
                    }]
                },
                files: [{
                    expand: true,
                    flatten: true,
                    src: ['<%= path.tmp %>/index.html', '<%= path.tmp %>/m.js', '<%= path.tmp %>/s.css'],
                    dest: '<%= path.tmp %>'
                }]
            }

        },
        concat: {
            // options: {
            //  process: function(src, filepath) {
            //      return '//####\n' + src;
            //  }
            // },
            dist: {
                src: ['<%= path.dev %>/js/*.js', '!<%= path.dev %>/js/app.js', '!<%= path.dev %>/js/jquerymin.js', '!<%= path.dev %>/js/manifest.js'],
                dest: '<%= path.tmp %>/m.js'
            }
        },
        imagemin: {
            dist: {
                options: {
                    optimizationLevel: 3,
                    cache: false
                },
                files: [{
                    expand: true,
                    cwd: '<%= path.dev %>/images',
                    src: '{,*/}*.{png,jpg,jpeg,gif}',
                    dest: '<%= path.tmp %>'
                }]
            }
        },
        autoshot: {
            default_options: {
                options: {
                    path: '<%= path.dev %>/images',
                    filename: 'Backup',
                    type: 'PNG',
                    remote: '',
                    local: {
                        path: '<%= path.dist %>',
                        port: 8080,
                        files: [{
                            src: "index.html",
                            dest: "Backup.jpg",
                            delay: 20000
                        }]
                    },
                    viewport: ['300x250']
                }
            }
        },
        copy: {
            post: {
                files: [{
                    expand: true,
                    dot: true,
                    cwd: '<%= path.tmp %>',
                    dest: '<%= path.dist %>/',
                    src: ['*.*']
                }]
            },
            post_ad: {
                files: [{
                    expand: true,
                    dot: true,
                    cwd: '<%= path.tmp %>',
                    dest: '<%= path.extra %>/',
                    src: ['*.*']
                }]
            },
            pre: {
                files: [{
                    expand: true,
                    flatten: true,
                    cwd: '<%= path.dev %>',
                    src: ['index.html', 'js/manifest.js', 'js/jquerymin.js'],
                    dest: '<%= path.tmp %>'
                }]
            }
        },
        cssmin: {
            dist: {
                files: {
                    '<%= path.tmp %>/s.css': [
                        '<%= path.tmp %>/styles/{,*/}*.css',
                        '<%= path.app %>/styles/{,*/}*.css'
                    ]
                }
            }
        },
        uglify: {
            mangle: {
                except: ['jQuery']
            },
            dist: {
                files: {
                    '<%= path.tmp %>/m.js': ['<%= path.tmp %>/m.js']
                }
            },
            pre: {
                files: {
                    '<%= path.tmp %>/js/scripts.js': ['<%= path.dev %>/js/scripts.js']
                        /*,
                    '<%= path.tmp %>/js/lib.js': ['<%= path.dev %>/js/lib.js']*/
                }
            }
        },
        'usemin-handler': {
            html: 'index.html'
        },
        htmlmin: {
            dist: {
                options: {},
                files: [{
                    expand: true,
                    cwd: '<%= path.tmp %>',
                    src: '*.html',
                    dest: '<%= path.tmp %>'
                }]
            }
        },
        useminPrepare: {
            html: '<%= path.app %>/index.html',
            options: {
                dest: '<%= path.tmp %>'
            }
        },
        usemin: {
            html: ['<%= path.tmp %>/{,*/}*.html'],
            css: ['<%= path.tmp %>/{,*/}*.css'],
            options: {
                dirs: ['<%= path.tmp %>']
            }
        },
    });

    // These plugins provide necessary tasks.
    require('load-grunt-tasks')(grunt);

    // Default task.
    grunt.registerTask('default', ['build', 'cachebreaker']);
    grunt.registerTask('build', [
        'clean',
        'config:prod',
        'replace:env',
        'compass:dist',
        'useminPrepare',
        'uglify:pre',
        'concat',
        'copy:pre',
        'imagemin',
        'htmlmin',
        'cssmin',
        'replace:env',
        'replace:post',
        'usemin',
        'copy:post',
    ]);

    grunt.registerTask('serve', function(target) {
        if (target === 'dist') {
            return grunt.task.run(['build', 'open:server', 'compass:server', ]);
        }

        grunt.task.run([
            'config:dev',
            'clean:server',
            'replace:env',
            'compass:server',
            'connect:livereload',
            'open:server',
            'watch'
        ]);
    });
    grunt.registerTask('backup', ['build',
        'autoshot'
    ]);

}
`
