### ISSUE TITLE
How to abort/kill grunt-contrib-watch on purpose?

### ISSUE THREAD

**Issue by johannesjo** [gruntjs/grunt-contrib-watch#385]
Sorry for the weird naming, but I wanted to clearly distinguish my question from all the questions, which are about grunt aborting without the user wanting it to.

I'm on the other hand trying to kill the current instance of grunt via a task to prevent grunt from messing up, if there are accidently more than one instance running at the same time (e.g. build and watch). I tried to use grunt.fail.fatal but the watch task stillcontinues running.

```
grunt.task.registerTask('KILL', 'KILL KILL KILL.', function() {
    grunt.fail.fatal('Aborted grunt to prevent conflicts in _config.js.');
});

...
watch:{
        preventConfigConflicts:{
            files: [appConfig.configFilePath],
            tasks:[
                'KILL'
            ]
        }  
}
```

Any ideas how to achieve that?

I also tried nodes process.exit without any effect:

```
grunt.task.registerTask('KILL', 'KILL KILL KILL.', function() {
    process.exit(code=1);
});
```

**Comment by dhawalbhanushali** [comment]
@shama process.exit(1); works for me. Thank you so much!
