### ISSUE TITLE
Run included tasks after 'watch' eventListener

### ISSUE THREAD

**Issue by nikoloza** [gruntjs/grunt-contrib-watch#387]
Hello,

I'm trying to run shell command when file changes. Getting last changed file to use as argument for shell command. Here is the code: https://gist.github.com/nikoloza/515f4d4cac656cbe2594. 

'watch' eventListener actually works, but it does after shell command runs. How can I run task before event has been triggered?

Thanks

**Comment by tommyJS** [comment]
+1

**Comment by nikoloza** [comment]
@tommyJS https://gist.github.com/nikoloza/515f4d4cac656cbe2594 here I have working example

**Comment by nikoloza** [comment]
@tommyJS https://gist.github.com/nikoloza/515f4d4cac656cbe2594 I've got working example here
