### ISSUE TITLE
files property required when it makes no sense for having it

### ISSUE THREAD

**Issue by Izhaki** [gruntjs/grunt-contrib-watch#400]
I'm using `atBegin` to launch a karma server upon watch (see full Gruntfile.js [here](http://stackoverflow.com/questions/27602746/)):

```
watch: {
    initialise: {
        files: [], // This is redundant, but we get an error if not specifying files.
        tasks: [ 'karma:continuous:start' ],
        options: {
            atBegin: true,
            spawn: false
        }
    },

    ...
}
```

In this specific case, I simply want a task to run at the startup of the watcher, regardless of any files. But if one removes the `files` property, one gets:

```
Waiting...Verifying property watch.initialise.files exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch.initialise.files" missing.
```

I wonder it makes sense to look for the `files` property if the `atBegin` option is defined?

**Comment by smarts** [comment]
Why not just just register it in your default task?:
`grunt.registerTask('default', ['task that runs at the beginning', 'watch']);`
