### ISSUE TITLE
Multiple watch tasks with different variable needs 

### ISSUE THREAD

**Issue by msrafi** [gruntjs/grunt-contrib-watch#407]
I have 3 different tasks with an different variables. When I call one of the task its looking for other variables as well.

```javascript
           sassUpdate: {
                options: {
                    spawn: false,
                    livereload: false
                },
                files: '../themes/ud<%= sassy.udVersion %>_atom/css/**/*.scss',
                tasks: ['sass:sassyCheck', 'copy:sassUpdateCopy']
            },
            buildProj: {
                options: {
                    spawn: false,
                    livereload: true,
                },
                files:['./<%= build.projName %>/index.html', './<%= build.projName %>/**/*'],
                tasks: ['sass:sassyCheck']
            },
            combineJS: {
                options: {
                    spawn: false,
                    livereload: false
                },
                files: '../themes/ud<%= combineJS.udVersion %>_atom/js/*.js',
                tasks: ['concat:ud']
            }
```

**Comment by sindresorhus** [comment]
What you're asking is not clear. Please clarify.

**Comment by arkoak** [comment]
This seems similar to what I had in mind . I want to run watch tasks based on what part of code im developing . 
Following is an excrept from my config file. 
<pre>
        docco: {
            files: ['api/controllers/*.js''], 
            tasks: ['docco']
        },
        jsdoc: {
            files: ['api/controllers/*.js'], 
            tasks: ['jsdoc']
</pre>

I do not want to run both jsdoc and docco all the time, I only want to run them on specific times when im working on improving my documentation, it would be great if I could provide a parameter to the watch command , something like
<pre>
grunt watch docco
grunt watch jsdoc 
</pre>
supporting one or more parts of the config to watch for at a time , that would really help in selective watching without commenting / uncommenting the config all the time.

**Comment by shama** [comment]
@arkoak You can do `grunt watch:docco` to run it individually.

@msrafi I am assuming by variables you mean templates: ie, `<%= build.projName %>`. Those are all evaluated by Grunt at runtime irregardless of task.

**Comment by arkoak** [comment]
great thanks, should be part of the readme.
