### ISSUE TITLE
Trigger livereload as soon as all livereload enabled tasks have been completed?

### ISSUE THREAD

**Issue by davidparsson** [gruntjs/grunt-contrib-watch#411]
We're using `watch` to among other things compile TypeScript, lint our code and run our unit tests.

Since our lint checks and test execution takes a few seconds, I created two watch targets for the same file sets. One of them does the preparations needed for the live reload with `livereload: true`, and the other one runs the slower tasks with `livereload: false`, as outlined below.

    {
      watch: {
        compileTypeScript: {
          files: ["app/**/*.ts"],
          tasks: ["typescript"],
          options: {
            livereload: true
          }
        },
        verify: {
          files: ["app/**/*.ts"],
          tasks: ["karma", "tslint"],
          options: {
            livereload: false
          }
        }
      },
      // ...
    }

I hoped that the live reload would be triggered after `watch:compileTypeScript` but before `watch:verify` was executed. Is this supported somehow?

**Comment by shama** [comment]
Create a live reload target that watches the files that **will trigger the live reload**. Such as where the destination files that typescript is compiling to.

**Comment by davidparsson** [comment]
You mean like this? The JavaScript files are created in `build/`  by the TypeScript compiler.

    {
      watch: {
        options: {
          livereload: false
        },
        reloadClient: {
          files: ["build/**/*"],
          options: {
            livereload: true
          }
        },
        compileTypeScript: {
          files: ["app/**/*.ts"],
          tasks: ["typescript"]
        },
        verify: {
          files: ["app/**/*.ts"],
          tasks: ["karma", "tslint"]
        }
      },
      // ...
    }

The live reload is still triggered _after_ both `watch:compileTypeScript` and `watch:verify` are completed, not before `watch:verify`.

**Comment by shama** [comment]
Correct. There isn't an existing API for handling the use case your after though. See this issue: #186.

You can trigger the live reload manually though within a custom task. Then put that custom task anywhere in a task chain though. That is probably the best solution atm.

**Comment by davidparsson** [comment]
Oh, there was an issue for it already. I didn't find it in my searches before reporting. Thanks for your help!
