### ISSUE TITLE
Feature Suggestion: expire / timeout option

### ISSUE THREAD

**Issue by evvvritt** [gruntjs/grunt-contrib-watch#428]
Hi, 

It would be great to have an option for the watch task to expire or timeout after a certain amount of time. 

Often times I forget I get distracted or end my work session without remembering to terminate grunt watch. Keeping it running seems to take a significant amount of energy / processing so it would be great to be able to set a timeout.

Thanks

**Comment by sindresorhus** [comment]
```
grunt watch & sleep 3600; kill $!
````

**Comment by evvvritt** [comment]
Ah, thanks sindresorhus. Do you have any insight into how I might register that line into a task? I didn't find the GruntJS.com guide helpful.
