### ISSUE TITLE
How to run less task on all files that watch detects?

### ISSUE THREAD

**Issue by hholhjem** [gruntjs/grunt-contrib-watch#432]
I am trying to set up a config where I combine watch and less.

I have tried to follow the similar setup as @shama did here: https://github.com/gruntjs/grunt-contrib-watch/issues/65#issuecomment-15472798 with watch and jshint. But it looks like it is not done in the similar way. 

Is it at all possible to set up watch to work together with less so that less compiles all .less files that watch detects?

All help and hints appreciated!

**Comment by shama** [comment]
Yes you can. If you need specific help debugging your Gruntfile I would ask on stackoverflow.com. They are a better resource when looking for support. This issue tracker is mostly for discussing issues with this task. Thanks!

**Comment by hholhjem** [comment]
Please feel free to check out this question:
http://stackoverflow.com/questions/29817216/grunt-how-to-generically-run-less-task-on-multiple-files-that-the-watch-task-de
Thanks!

**Comment by hholhjem** [comment]
Still trying to figure out if grunt-contrib-watch supports this issue. Sorry to bother you @shama, but i hope tagging you increases chance of finding an answer.

How can I set up my grunt script to run a less task on multiple files that the watch task detects? Is it possible to do this without using a "grunt.event.on('watch'..." hack?

This solution works with one file, but when two files are saved at the same time (in Visual Studio) only one css is generated.

The script:

	'useStrict';
	module.exports = function (grunt) {
		grunt.initConfig({
			globalConfig: globalConfig,
			less: {
				all: {
					options: {
						compress: false,
					},
					files: '',
				},
			},
			watch: {
				all: {
					files: [
							'Main/**/*.less',                       
					],
					tasks: ['less'],
					options: {
						nospawn: true
					}
				}
			}       
		});

		grunt.loadNpmTasks('grunt-contrib-less');
		grunt.loadNpmTasks('grunt-contrib-watch');

		grunt.event.on('watch', function(action, filepath) {

			// Handling .less imports so that when the watch task
			// detects change in an imported file, "the main .less file
			// that does the import" is compiled, instead of the imported file.
			// Naming convention for imported files: Title of main file that 
			// imports + "-" + name describing the imported file
			// E.g. Main.less, Main-Colors.less, Main-Structure.less, Main-Utility.less

			var splittedPath = filepath.split('/');
			var filename = splittedPath[splittedPath.length - 1];
			delete splittedPath[splittedPath.length - 1];
			var fileDirectoryPath = splittedPath.join('/');
			var splittedFilename = filename.split('-');
			if (splittedFilename.length > 1){
				filepath = fileDirectoryPath + splittedFilename[0] + '.less';
			}

			grunt.config(['less', 'all', 'files'], [{
				expand: true,
				src: filepath,
				ext: '.css',
			}]);
		});

		grunt.registerTask('default', ['watch']);
	};

All help appreciated! Thanks!

**Comment by shama** [comment]
@hholhjem It could be because you're not specifying a `dest` on your `less` config. Also the `watch` event gets fired for each file. So if your saving multiple files at once, you'll need to account for that, see: https://github.com/gruntjs/grunt-contrib-watch#compiling-files-as-needed

Also by that point, it will likely be better to use a bundler that is aware of the dependency graph of less. This watch task is not. I don't use less so I'm not aware of any specific solution, sorry.

**Comment by hholhjem** [comment]
@shama Thank you!! That helped me solve the problem!
