### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by mmucklo** [gruntjs/grunt-contrib-watch#458]
I have the unfortunate task of confirming licenses on software, so I hate to bring up this rather pedantic issue, however installing 0.6.1 installs tiny-lr-fork 0.0.5 which installs noptify which is presently unlicensed on npmjs.com.

There is a license file in the repo on github, however there's no published version that has a license file, which results in unlicensed software being pulled in when one installs grunt-contrib-watch via npm.

I have an open issue with the maintainer of this repo, so hopefully they will just publish a new version, and be done with it - I would appreciate any thumbs-up on the issue so it may come to their attention.  However it seems that releasing the latest version of grunt-contrib-watch may fix the problem as it now uses tiny-lr.

https://github.com/mklabs/noptify/issues/7

Thanks
Matt

**Comment by XhmikosR** [comment]
/CC @vladikoff: maybe sort the test failures and release a new version?

**Comment by shama** [comment]
Tests are now passing again and a new version will be release shortly.
