### ISSUE TITLE
Could we release a new version?

### ISSUE THREAD

**Issue by bhamodi** [gruntjs/grunt-contrib-watch#466]
Hi there,

There's been quite a few commits since the last release which was in 2014 - could we release a new version? If there are any blockers, I'd be willing to help!

Thanks!

**Comment by bhamodi** [comment]
@vladikoff - do you have access to this NPM as well?

**Comment by vladikoff** [comment]
@bhamodi there are blockers, @shama knows which blockers are blocking

**Comment by shama** [comment]
The tests are failing. Currently that is the only thing holding up a new release of `master`.

**Comment by paladox** [comment]
According to the tag on the readme file the error is coming from https://github.com/gruntjs/grunt-contrib-watch/pull/467/files and affects the node_js versions 0.12 and 4.

**Comment by paladox** [comment]
It is coming up with these errors

983ERROR

984>> Message: Task should have been interrupted 2 times.

985>> Error: false == true

986>> at Object.ok (node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/types.js:83:39)

987>> at /home/travis/build/gruntjs/grunt-contrib-watch/test/tasks/watch_test.js:143:12

988>> at ChildProcess.<anonymous> (test/tasks/helper.js:84:7)

989>> at ChildProcess.emit (events.js:110:17)

990>> at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

991

992>> Message: Only the last time should be working (without interruption)

993>> Error: null == true

994>> at Object.ok (node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/lib/types.js:83:39)

995>> at /home/travis/build/gruntjs/grunt-contrib-watch/test/tasks/watch_test.js:145:12

996>> at ChildProcess.<anonymous> (test/tasks/helper.js:84:7)

997>> at ChildProcess.emit (events.js:110:17)

998>> at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

999

1000watch - failingTask...Running "watch" task

1001Waiting...

1002>> File "lib/fail.js" changed.

1003Running "echo:fail" (echo) task

1004Fatal error: This task should fail

1005Completed in 1.495s at Thu Oct 29 2015 12:59:25 GMT+0000 (UTC) - Waiting...

**Comment by joh-klein** [comment]
The same test was already failing on v0.6.1 (as far as I can tell), so why bother now? Another downside of not pushing to npm: right now you are advertising features that are not really there (to be fair, you only advertise theme on github, but still under the v0.6.1 banner!). Specifically: the options.cwd.event option. I NEED that …

**Comment by shama** [comment]
@joh-klein You can install the latest on master from github, `npm i gruntjs/grunt-contrib-watch`.

I'm not publishing a version that I know has failing tests. The tests were not failing when I published `0.6.1`: https://travis-ci.org/gruntjs/grunt-contrib-watch/builds/21126466

**Comment by joh-klein** [comment]
@shama OK, when you published, they were not failing. But if you check the v0.6.1 tag out now, they fail as well?

I took a stab at the tests, and got it down to one failing test. Not the prettiest of solutions … I'll post a PR anyways so you can have a look.

**Comment by shama** [comment]
@joh-klein I appreciate your intent to help but I'm not looking for band aids. `0.6.1` was released 2 years ago. I rigorously tested on Windows, Linux and OSX with the 2 major versions of Node.js at the time, `v0.8` and `v0.10`.

Keep in mind this library is downloaded via npm over 700,000 times a month. Publishing should not be taken lightly. The landscape has gotten more complex. We now have to support a lot more versions of Node.js and operating systems. Actual sincere work needs to be done to make that happen.

If you don't agree with my publishing standards then by all means install directly from github: `npm i gruntjs/grunt-contrib-watch`.

**Comment by shama** [comment]
A new version will be release shortly now that tests are passing.
