### ISSUE TITLE
Grunt watch stops noticing changes after switching git branch

### ISSUE THREAD

**Issue by FireArrow** [gruntjs/grunt-contrib-watch#471]
If you watch a file tracked by git, watch will stop noticing changes after switching git branch.

Steps to reproduce:
```
grunt watch &
touch tracked-file
# Watch triggers, as expected
git checkout some-other-branch
touch tracked-file
# Watch doesn't trigger
```

Relevant software versions:
* grunt-contrib-watch: 0.6.1
* grunt-cli v0.1.13
* grunt v0.4.5
* node v4.1.1

**Comment by shama** [comment]
This works for me. Are you sure it is watching the files git is switching out?

**Comment by sindresorhus** [comment]
Closing for lack of response by OP.
