### ISSUE TITLE
Not working in Node 4

### ISSUE THREAD

**Issue by estvmachine** [gruntjs/grunt-contrib-watch#475]
Hi, im observing this plugin doesnt work in Node 4. Can you update a version can

**Comment by shama** [comment]
Could you describe what isn't working? Or any error messages you are getting? It is working for me.

**Comment by ali-bugdayci** [comment]
Hi,

Upgrade ready also marks it as failing too. 

http://upgrade-ready.nodesource.com/summary/0a8433f0-936e-11e5-ab3c-3bac1dbd8d71

**Comment by vladikoff** [comment]
upgrade-ready says "ENOENT: no such file or directory, stat '/tmp/4.2.2/grunt-contrib-watch@0.6.1/output.log'" wat does that mean

**Comment by ali-bugdayci** [comment]
I believe its the log that had been produced when trying to use grunt-contrib-watch on 4.2.

 It can not produce an output.log file, that is similar to the one produced with grunt.(check the site for grunt output)

By the way the output is useless, I aggree :)

**Comment by shama** [comment]
Tests are passing on Node 4.
