### ISSUE TITLE
why gruntfile not created my new file

### ISSUE THREAD

**Issue by shubh93** [gruntjs/grunt-contrib-watch#480]
require:
      almond:
        options:
          baseUrl: './dst/frontend'
          out: './dst/frontend/libs/almond.build.js'
          name: './dst/frontend/libs/almond/almond'
          include: 'webapp'
          mainConfigFile: './dst/frontend/js/webapp.js'

**Comment by shubh93** [comment]
please reply i need help thankyou

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
