### ISSUE TITLE
Pleas update tiny-lr (again)

### ISSUE THREAD

**Issue by plynchnlm** [gruntjs/grunt-contrib-watch#482]
tiny-lr needs to be at least 0.2.0 (0.2.1 is also out) or it pulls in an old version of debug which pulls in a version of ms which has a [vulnerability](https://nodesecurity.io/advisories/46).

**Comment by andersevenrud** [comment]
I'd like to see this resolved as well. Is there any reason for not upgrading ?

**Comment by lirantal** [comment]
+1

**Comment by shama** [comment]
Done on fe4959f48fe948e37984a0d6f4bd322cfb5ff3c4

**Comment by andersevenrud** [comment]
@shama When can we expect a version bump ? :)
