### ISSUE TITLE
interrupt does not wait for spawned process to finish

### ISSUE THREAD

**Issue by fenderle** [gruntjs/grunt-contrib-watch#484]
When interrupt is set to true and a process is spawned (spawn: true) there is a race condition.
1. on interrupt task.complete() is called and sends SIGINT to the spawned process
2. it then does not wait until the child process is really dead, but instead continues execution
3. the (new) process gets started (while the old one is still running)
4. the previous process finishes, causing all callbacks to fire and messing up the state of the task object

Though this can be mediated by some simple flags it is still a problem and can lead to resource problems, eg. when the spawned child sets up a listening socket while the previous child is still running. Also the output buffers are gone in this case.

To fix the issue it is required to layout all the complete() functions (taskrun.complete() and taskrunner.complete()) to work with callbacks, which is a major pain (I tried, but eventually gave up due to the complexity of the change).

However this is imho a major bug which leads to all kind of strange behaviour.

**Comment by davidminor** [comment]
Looks like the problem here is that the interrupted task is not supposed to call done(), but grunt when interrupted returns status code 0 rather than 130, so done is called.
