### ISSUE TITLE
Watch stops working from time to time 

### ISSUE THREAD

**Issue by eskimoblood** [gruntjs/grunt-contrib-watch#49]
After having run the task for about 10 minutes it stops to recognize file changes. Most of the time the last change on a file was printed in the console like this:

```
File "Gruntfile.js" deleted.
```

even it was a change in the file. After that any change in the file cant bring the watcher back to run the tasks.

**Comment by naniaryan** [comment]
Hey did anyone found, temporary **fix** or **solution** ?

**Comment by FlavorScape** [comment]
grunt-cli v1.2.0
grunt v0.4.5

grunt randomly quits watch somewhere between 10-30 minutes ...

**Comment by FlavorScape** [comment]
Still happens. Randomly quits after 10-min or 1 hour. no pattern to it. I use grunt with typescript compiler among other things.

**grunt-contrib-watch 1.0.0
grunt-cli v1.2.0
node 4.0.0**
