### ISSUE TITLE
Release 0.6.2 that has grunt >=0.4.x peerDep

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-contrib-watch#491]
No need for any other changes, just that fix

@shama let me know if that makes sense and I can do the rest

**Comment by shama** [comment]
With >=4 of Node.js, this plugin has some issues. I think we need to fix those first. I was hoping to get to it before `grunt@1.0.0` drops.

**Comment by hildjj** [comment]
Any progress?

**Comment by vladikoff** [comment]
This was done in https://github.com/gruntjs/grunt-contrib-watch/commit/1f198f6ec849cc69ac74b24af9362592dd2d610a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 

released with 1.0.0 version of the plugin
