### ISSUE TITLE
Is it possible to watch a database for changes?

### ISSUE THREAD

**Issue by neocamel** [gruntjs/grunt-contrib-watch#503]
This might be a dumb question, but I was thinking it would be pretty neat if making changes to the database would also trigger the watch function.  I do a lot of Wordpress dev, and that would be really helpful to have the page I'm working on reload if I make any changes to the content (ie. database) of that page.

**Comment by vladikoff** [comment]
This is out of scope for this module (The scope is "Run tasks whenever watched files change."). You can create a grunt plugin that uses this module to watch for db changes in mysql: https://www.npmjs.com/package/mysql-events
