### ISSUE TITLE
Uncaught Error: [$injector:nomod] Module 'mean.modulename' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify th

### ISSUE THREAD

**Issue by shahfaisal91** [gruntjs/grunt-contrib-watch#505]
Hi All, 
When I create a custom package and run "bower install my-package-name /path-to-pachkage"
and run the application using gulp , it says following errors:
can any one help please?

angular.js:68Uncaught Error: [$injector:nomod] Module 'mean.dashboard' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=mean.dashboard(anonymous function) @ angular.js:68(anonymous function) @ angular.js:2070ensure @ angular.js:1994module @ angular.js:2068(anonymous function) @ dashboard.js:6(anonymous function) @ dashboard.js:1__webpack_require__ @ bootstrap 3f5fe3d…:19webpackContext @ tests|assets|views)(.*)\.js$:14processModules @ app.js:39fire @ jquery.js:3187self.fireWith @ jquery.js:3317done @ jquery.js:8785(anonymous function) @ jquery.js:9151send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684(anonymous function) @ app.js:46__webpack_require__ @ bootstrap 3f5fe3d…:19(anonymous function) @ bootstrap 3f5fe3d…:39__webpack_require__ @ bootstrap 3f5fe3d…:19(anonymous function) @ bootstrap 3f5fe3d…:39(anonymous function) @ bootstrap 3f5fe3d…:39
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:nomod] Module 'mean' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.5/$injector/nomod?p0=mean
    at http://localhost:3000/bundle/app.js:10506:13
    at http://localhost:3000/bundle/app.js:12508:18
    at ensure (http://localhost:3000/bundle/app.js:12432:39)
    at module (http://localhost:3000/bundle/app.js:12506:15)
    at http://localhost:3000/bundle/app.js:15002:23
    at forEach (http://localhost:3000/bundle/app.js:10760:21)
    at loadModules (http://localhost:3000/bundle/app.js:14986:6)
    at createInjector (http://localhost:3000/bundle/app.js:14908:20)
    at doBootstrap (http://localhost:3000/bundle/app.js:12184:21)
    at Object.bootstrap (http://localhost:3000/bundle/app.js:12205:13)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=mean&p1=Error%3A%20….bootstrap%20(http%3A%2F%2Flocalhost%3A3000%2Fbundle%2Fapp.js%3A12205%3A13)(anonymous function) @ angular.js:68(anonymous function) @ angular.js:4587forEach @ angular.js:322loadModules @ angular.js:4548createInjector @ angular.js:4470doBootstrap @ angular.js:1746bootstrap @ angular.js:1767(anonymous function) @ app.js:25trigger @ angular.js:3166defaultHandlerWrapper @ angular.js:3456eventHandler @ angular.js:3444

**Comment by vladikoff** [comment]
> and run the application using gulp 

Wrong project.  This is a grunt plugin
