### ISSUE TITLE
Unable to install the sass using NPM

### ISSUE THREAD

**Issue by ynr1** [gruntjs/grunt-contrib-watch#526]
ERROR:  Could not find a valid gem 'sass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ETIMEDOUT:
 A connection attempt failed because the connected party did not properly respon
d after a period of time, or established connection failed because connected hos
t has failed to respond. - connect(2) for "api.rubygems.org" port 443 (https://a
pi.rubygems.org/latest_specs.4.8.gz)

and ruby version is: ruby 2.1.6p336 (2015-04-13 revision 50298) [i386-mingw32]

Please help me, what are the steps I have to do ?

**Comment by shama** [comment]
This is the `grunt-contrib-watch` task. I recommend looking for the support channels for npm install issues for sass instead.
