### ISSUE TITLE
Where to go from here, or: is this dead?

### ISSUE THREAD

**Issue by joh-klein** [gruntjs/grunt-contrib-watch#537]
Since development for this has considerably "slowed down", I am wondering: 
* are there plans to add more maintainers? address the open issues? approve the open PRs?
* is there a fork that is actively maintained?
* are there other alternatives (or is everybody just using webpack these days?)

**Comment by SalTor** [comment]
+1

**Comment by darkship** [comment]
+1

**Comment by rnemec** [comment]
I switched to "grunt-chokidar" which at least uses much more CPU-friendly fs watching. But things are not easy - other plugins assume "watch" tasks are called "watch" not "chokidar". That addressed the high CPU aspect for me.

**Comment by deckar01** [comment]
None of the fork in the network graph seem to contain any improvements over the current master branch.

**Comment by shama** [comment]
I cannot answer any of the above questions nor think trying would be beneficial to anyone. It is what it is.
