### ISSUE TITLE
Would it be possible to stop the watcher while something is pulled from the repository via git?

### ISSUE THREAD

**Issue by vanBersie** [gruntjs/grunt-contrib-watch#549]
I was thinking about implementing a watcher for certain files in a repository. When a file is changed it should be automatically moved to the server and hot swap the old file. But let's say if I would do a pull request all the files would be renewed and be swapped to the server. 

How could I prevent this? Is it somehow possible to link the interrupt option with git activities (for example a pull request done by tortoise git)? Unfortunately I can't provide any code snippet since I only had theoretical thoughts about it. Could anyone provide some tips? 

Thanks in advance!

**Comment by shama** [comment]
Beyond stopping the watch task before you use git, I have no idea.
