### ISSUE TITLE
Security vulnerability in lodash@3.10.1

### ISSUE THREAD

**Issue by marcysutton** [gruntjs/grunt-contrib-watch#554]
There is a known security vulnerability in lodash@3x: https://hackerone.com/reports/310443

The severity is low, however grunt-contrib-watch should be updated to the latest lodash version to reduce risk.

**Comment by anutin544** [comment]
Ok

**Comment by anastasiagryshchenko** [comment]
came in here to report the same issue. it will make a huge difference if you could find time and deploy current master to npm

**Comment by shama** [comment]
Sorry for the delay, a new version of `grunt-contrib-watch@1.0.1` was published with the `lodash` dependency updated. Thanks!
