### ISSUE TITLE
grunt watch does not detect changes on scss partial files (files with '_' prefix)

### ISSUE THREAD

**Issue by hesamrasouli** [gruntjs/grunt-contrib-watch#556]
I use grunt watch for track the changes on *.scss files and *.js files.
It works great with *.scss files, but not working on scss partials(files with _ prefix) and does not trigger the tasks when I change my scss partials.I used * regex to detect all scss files changes in project Here is my watch configuration

`
 ... //emitted for the purpose of briefness
 watch: {
            scripts: {
                files: ['Assets/script/*.js', 'Assets/script/*/*.js', 'Assets/script/*/*/*.js'],
                tasks: ['webpack'],
                options: {
                    spawn: false,
                },
            },
            styles: {
                files: ['Assets/style/*.scss', 'Assets/style/*/*.scss', 'Assets/style/*/*/*.scss],
                tasks: ['webpack','cssmin'],
                options: {
                    spawn: false,
                }
            }
        },`
I also added `_*.scss` files explicitly like below

` ... //emitted for the purpose of briefness
  watch: {
 ... //emitted for the purpose of briefness
            styles: {
                files: ['Assets/style/*.scss', 'Assets/style/*/*.scss', 'Assets/style/*/*/*.scss',
                    'Assets/style/_*.scss', 'Assets/style/*/_*.scss', 'Assets/style/*/*/_*.scss'
                ],
                tasks: ['webpack','cssmin'],
                options: {
                    spawn: false,
                }
            }
        },` 
but didn't work.
Here is my whole `gruntfile.js` code

   `
var shared = require("./NodeUtils/bundler.sharedModules");
    const webpackConfig = require('./NodeUtils/webpack.dev');
    const env = shared.env.Dev;
    module.exports = function (grunt) {
    require("matchdep").filterDev("grunt-*").forEach(grunt.loadNpmTasks);

    // Project configuration.  
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        cssmin: {
            options: {
                sourceMap: true
            },
            sharedPlugins: shared.grunt.getStyleAssetObject(env, 'shared', shared.getVendorFile(env, shared.assetType.Style),
                shared.getTranspoiledAsset(env, shared.assetType.Style, shared.assetSource.Shared, 'sharedPlugins')),
           
        },
        watch: {
            scripts: {
                files: ['Assets/script/*.js', 'Assets/script/*/*.js', 'Assets/script/*/*/*.js'],
                tasks: ['webpack'],
                options: {
                    spawn: false,
                },
            },
            styles: {
                files: ['Assets/style/*.scss', 'Assets/style/*/*.scss', 'Assets/style/*/*/*.scss',
                    'Assets/style/_*.scss', 'Assets/style/*/_*.scss', 'Assets/style/*/*/_*.scss'
                ],
                tasks: ['webpack','cssmin'],
                options: {
                    spawn: false,
                }
            }
        },
        uglify: {
            options: {
                beautify: true,
                mangle: false,
                compress: false,
                sourceMap: true
            },
            sharedPlugins: shared.grunt.getScriptAssetObject(env, 'sharedPlugins', shared.bundles.scripts.shared.sharedPlugins),
            IEcompatible: shared.grunt.getScriptAssetObject(env, 'IEcompatible', shared.bundles.scripts.shared.IEcompatible),
        },
        webpack: {
            options: {
                stats: !process.env.NODE_ENV || process.env.NODE_ENV === 'development'
            },
            dev: Object.assign(webpackConfig)
        }
    });

    grunt.registerTask('default', ['webpack', 'uglify', 'cssmin']);
};`

**Comment by erperejildo** [comment]
what was the solution?
