### ISSUE TITLE
Why Watch is so slow compared to Regarde

### ISSUE THREAD

**Issue by kud** [gruntjs/grunt-contrib-watch#69]
Hello,

I don't know exactly what really happens but... I've got a freelance project, and people use "watch".

I'm on Windows and I use a virtual machine with ubuntu server to have a whole linux environment. I know, it's a quite tricky context.

However, watch is so slow to execute a task. It detects that I've changed a file but it does nothing during 20 or 30s, and then it starts the task.

I have changed Watch to Regarde and now it executes the task directly, no time to wait. Regarde is so efficient.

Any idea? NTFS troubles?

**Comment by ykadosh** [comment]
WOW, it's so much faster now! Why not set `spawn: false` to be the default setting? I just wonder what are the benefits of having `spawn: true`
