### ISSUE TITLE
New subfolders aren't watched until watch task is restarted

### ISSUE THREAD

**Issue by takempf** [gruntjs/grunt-contrib-watch#70]
If you watch a directory like so:

``` javascript
module.exports = function( grunt ){
    var pkg = grunt.file.readJSON( __dirname +'/package.json');
    grunt.initConfig({
        watch: {
            styles: {
                files: ['assets/**/*.css'],
                tasks: []
            }
        }
    });
    // The cool way to load Grunt tasks
    Object.keys( pkg.devDependencies ).forEach( function( dep ){
        if( dep.substring( 0, 6 ) === 'grunt-' ) grunt.loadNpmTasks( dep );
    });
    grunt.event.on( 'watch', function( action, filepath ){
        console.log( 'WATCH EVENT', action, filepath );
    });
};
```

The task will do nothing if you add a new folder, then add a new file inside of it:
- Create `assets/test/`
- Create `assets/test/test_file.css`
- Nothing happens :sob: 

If you restart the task, you'll be able to track the changes to files within that folder (but if you create any new folders, they will still be ignored until starting it again).

**Comment by khanh703** [comment]
@dinevillar Your solution worked for me.  Thank you!

**Comment by statyan** [comment]
This issue still exist. Can be reproduced if 'events' in options are set.
Tested for 0.6.1
with config:
'watch': {
            'controllers': {
                files: ['controllers/**/*Controller.js'],
                tasks: ['gen-include-controllers'],
                options: {
                    //event: ['added', 'deleted'],
                },
            }

If uncomment 'event' option, watcher would not watch newly created directories.

**Comment by statyan** [comment]
Hmm, seems to me it's not so simple. Only once i accidentally make watcher watch newly created directories. But for now it doesn't. First guess was increment Fedora fs.inotify.max_user_watches = 524288 but this does not help. Keep searching...

**Comment by rocket13531** [comment]
+1

**Comment by sl5net** [comment]
i also searching a solution for that: https://stackoverflow.com/questions/67507560/watch-folder-is-added-using-node
