### ISSUE TITLE
FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc()

### ISSUE THREAD

**Issue by jeremypeter** [gruntjs/grunt-contrib-watch#75]
I have an issue where on every 3rd save I get this: [ERROR](http://i.imgur.com/N859dnx.png)

It appears when I either save it 3 times within the same file or if I open up 3 different files, the error will appear afte the 3rd file has been saved. 

Here's my code: 

``` javascript
/*global module:false*/

var minimatch = require('minimatch');

module.exports = function (grunt) {

  grunt.initConfig({

    watch: {
      template: {
        files: '**/template.html',
        tasks: ['inlinecss', 'cssmin']
       },
       options: {
        nospawn: true
       }
      },
      cssmin: {
       minify: {
        files: [{
          src: 'template.html',
          dest: 'email.html'
         }]
        }
       },
       inlinecss: {
        main: {
         files: [{
          src: 'same_dir',
          dest: 'same_dir'
         }]
        }
       }
      });

  // Load tastks
  grunt.loadNpmTasks('grunt-contrib-cssmin');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-inline-css');

  // Default Task(s)
  grunt.registerTask('default', ['watch']);

  grunt.event.on('watch', function(action, filepath) {

    if (minimatch(filepath, grunt.config('watch.template.files'))) {

     // Current Working Directory
     var cwd = filepath.replace(filepath.substr(filepath.lastIndexOf('/') + 1), '');

     // Destination
     var dest = cwd + 'email.html';

     grunt.config('inlinecss.main.files.0.src', [filepath]);
     grunt.config('inlinecss.main.files.0.dest', dest);
     grunt.config('cssmin.minify.files.0.src', [filepath]);
     grunt.config('cssmin.minify.files.0.dest', dest);

    }
   });

 };
```

I basically have a folder structure that contains a template.html and an email.html. I work within the template.html and on every save, it creates the email.html that inlines the css and minifies the code.

**Comment by ggranum** [comment]
For future visitors from Google: check that you're not accidentally including bower or node_modules directories :~)  Oops! 

Just add `"!**/node_modules/**/*"` (or whatever) to the end of your watch globs array if you're not sure. There's also another comment in this list that details how to list all the [watched files](https://github.com/gruntjs/grunt-contrib-watch/issues/75#issuecomment-30675205). 

I ran into this using gulp with a watch. Commenting here because this is the first Google result for the error, and it's relevant.

**Comment by mattii** [comment]
Thanks @ggranum ! Works for me.

**Comment by gad2103** [comment]
thanks everyone! this SMA!

**Comment by lusitong** [comment]
@ggranum  thank you

**Comment by vink3d** [comment]
ggranum thank you, this solve problems :)

**Comment by Anaphase** [comment]
Thanks @ggranum!

**Comment by EvanLovely** [comment]
Avoid watching items in the "bower_components" folder too.

```json
[
  "!**/node_modules/**/*",
  "!**/bower_components/**/*"
]
```

**Comment by dclowd9901** [comment]
How can this possibly be closed? "Watch fewer files" is not a solution, nor is excluding node_modules folders. What if my org has a module that has a linked module where we develop our sass code?

**Comment by shama** [comment]
@dclowd9901 We accept pull requests if you know a better solution.

**Comment by chetangautam** [comment]
@EvanLovely Where should I add these to avoid watching? Thanks!

**Comment by EvanLovely** [comment]
@chetangautam Add them anywhere you're declaring files to watch.

**Comment by chetangautam** [comment]
@EvanLovely Thanks!
