### ISSUE TITLE
Livereload CSS without browser refresh

### ISSUE THREAD

**Issue by darvelo** [gruntjs/grunt-contrib-watch#87]
I've been playing with the new livereload feature and it's pretty easy to use. Thanks for putting it in. :)

I'm stumbling into an issue where a livereload of css changes will sometimes refresh the page, and sometimes not. I'm not sure why, though. It would be awesome if it never triggered a refresh since it makes for faster dev. A quick sample of my Gruntfile:

``` javascript
watch: {
  compass: {
    files: ['<%= yeoman.app %>/styles/{,*/}*.{scss,sass}'],
    tasks: ['compass:server'],
  },
  css: {
    files: [
      '{.tmp,<%= yeoman.app %>}/styles/**/*.css',
    ],
    tasks: ['noop'],
    options: {
      livereload: true
    },
  },
}
```

Any ideas why this might be happening? I've tweaked settings back and forth but can't seem to pin down the cause.

**Comment by kirillgroshkov** [comment]
still no fix for this? Having the same issue

**Comment by x1024** [comment]
@kirillgroshkov the grunt-concurrent thing works (it was suggested earlier in the thread).
Here is some more info: http://stackoverflow.com/a/18191735/140786

**Comment by artuska** [comment]
I have tried all those `spawn: true|false` tricks and none of them is working in September 25th, 2016. (`grunt-concurrent` is totally offtopic — it have nothing to do with CSS soft reloading).

**Comment by jetlej** [comment]
Not working here either
