### ISSUE TITLE
Server for livereloading is not running

### ISSUE THREAD

**Issue by dmitriy-baltak** [gruntjs/grunt-contrib-watch#97]
I'm new to Grunt and trying to configure watch livereload but can't figure out why am I keep recieving message
{"tinylr":"Welcome","version":"0.0.4"}
on the http://localhost:35729/

I've tryed to install  a plugin for Chrome that is mentioned in readme and adding a script tag manually in html before </body> but it doesn't help.

**Comment by blackcoat77** [comment]
When I try to reload the page in the browser from localhost, I'm getting the code 101 (switching protocols) from the headers. It says livereload GET 101 pending. It happens many time that when I reload the page I don't see any results..I'm getting very long delay to print the result from my IDE to browser. I'm really wondering why is this happen? Do you have any idea? Thanking you in advance.

**Comment by inviolablegenesis** [comment]
@blackcoat77 did you solve your problem? i'm having the same problem.

**Comment by blackcoat77** [comment]
Nope! Unfortunately I haven't.

**Comment by chengsu** [comment]
@blackcoat77 I've met the same problem.
Try use `<script src="http://127.0.0.1:3000/livereload.js"></script>` in the html file,and change the livereload port to 3000.This works for me.

**Comment by landed1** [comment]
I found on initial grunt build the server works with localhost however it was dying showing the string as in the issue...having to run grunt each time defeats the idea. I did find using 127.0.0.1 works for me so far.

**Comment by sudhansurana** [comment]
any solution yet?

my issue is same as blackcoat77 .
